import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // suppressHydrationWarning helps avoid React hydration warnings when
        // the browser (or an extension) mutates attributes between SSR and client boot.
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
        <div className="app-root min-h-screen flex flex-col">

            <Header />

          <div className="container mx-auto px-6 py-8 flex-1 w-full">
            <div className="layout-grid grid grid-cols-1 sm:grid-cols-[220px_1fr] gap-6">
              <aside className="sidebar hidden sm:block">
                <div className="p-4 rounded-md border bg-[color:var(--panel)]">
                  <h3 className="font-semibold mb-3">Browse</h3>
                  <ul className="space-y-2 text-sm">
                    <li><a className="block hover:underline" href="#">All books</a></li>
                    <li><a className="block hover:underline" href="#">New arrivals</a></li>
                    <li><a className="block hover:underline" href="#">Top rated</a></li>
                    <li><a className="block hover:underline" href="#">Categories</a></li>
                  </ul>
                </div>
              </aside>

              <main className="main-content">{children}</main>
            </div>
          </div>

          <footer className="site-footer w-full border-t">
            <div className="container mx-auto px-6 py-4 text-sm text-[color:var(--muted)]">
              © {new Date().getFullYear()} Library — Built with Next.js
            </div>
          </footer>
        </div>
          </AuthProvider>
      </body>
    </html>
  );
}
